src/recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/recipes/urls.py
from django.urls import path
from .views import home, RecipeListView, RecipeDetailView, records
from django.views.generic import RedirectView

app_name = 'recipes'


urlpatterns = [
    path("", RedirectView.as_view(url="home/")),
    path('home/', home, name='home'),
    path('recipes/list/', RecipeListView.as_view(), name='list'),
    path('recipes/list/<pk>', RecipeDetailView.as_view(), name='detail'),
    path('recipes/search', records, name='records')
]

src/recipes/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.

class Recipe(models.Model):
    name = models.CharField(max_length=120)
    cooking_time = models.FloatField(help_text='in minutes')
    difficulty = models.CharField(max_length=50, default='unknown')
    ingredients = models.TextField()
    pic = models.ImageField(upload_to='recipes', default='no_picture.jpg')

    def __str__(self):
        return str(self.name)

    def calculate_difficulty(self):
        ingredients = self.ingredients.split(', ')
        
        if self.cooking_time < 10 and len(ingredients) < 4:
            difficulty = 'Easy'
        elif self.cooking_time < 10 and len(ingredients) >= 4:
            difficulty = 'Medium'
        elif self.cooking_time >= 10 and len(ingredients) < 4:
            difficulty = 'Intermediate'
        elif self.cooking_time >= 10 and len(ingredients) >= 4:
            difficulty = 'Hard'
        
        return difficulty

    
    def get_absolute_url(self):
        return reverse ('recipes:detail', kwargs={'pk': self.pk})

src/users/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=120)
    pic = models.ImageField(upload_to='users', default='no_picture.jpg')

    def __str__(self):
        return str(self.name)

src/recipes/forms.py
from django import forms  # import django forms

CHART__CHOICES = (  # specify choices as a tuple
    # when user selects "Bar chart", it is stored as "#1"
    ('#1', 'Bar chart'),
    ('#2', 'Pie chart'),
    ('#3', 'Line chart')
)

DIFFIC__CHOICES = (  # specify choices as a tuple
    # when user selects "Easy", it is stored as "#1"
    ('#1', 'Easy'),
    ('#2', 'Medium'),
    ('#3', 'Intermediate'),
    ('#4', 'Hard')
)

# define class-based Form imported from Django forms


class RecipesSearchForm(forms.Form):
    recipe_diff = forms.ChoiceField(choices=DIFFIC__CHOICES)
    chart_type = forms.ChoiceField(choices=CHART__CHOICES)

src/recipe_project/views.py
from django.shortcuts import render, redirect
# Django authentication libraries
from django.contrib.auth import authenticate, login, logout
# Django Form for authentication
from django.contrib.auth.forms import AuthenticationForm

# define a function view called login_view that takes a request from user


def login_view(request):
    # initialize:
    # error_message to None
    error_message = None
    # form object with username and password fields
    form = AuthenticationForm()

    # when user hits "login" button, then POST request is generated
    if request.method == 'POST':
        # read the data sent by the form via POST request
        form = AuthenticationForm(data=request.POST)

        # check if form is valid
        if form.is_valid():
            username = form.cleaned_data.get('username')  # read username
            password = form.cleaned_data.get('password')  # read password

            # use Django authenticate function to validate the user
            user = authenticate(username=username, password=password)
            if user is not None:  # if user is authenticated
               # then use pre-defined Django function to login
                login(request, user)
                # & send the user to desired page
                return redirect('recipes:list')
        else:  # in case of error
            error_message = 'ooops.. something went wrong'  # print error message

    # prepare data to send from view to template
    context = {
        'form': form,  # send the form data
        'error_message': error_message  # and the error_message
    }
    # load the login page using "context" information
    return render(request, 'auth/login.html', context)

# define a function view called logout_view that takes a request from user


def logout_view(request):
    logout(request)  # the use pre-defined Django function to logout
    # after logging out go to login form (or whichever page you want)
    # return redirect('login')
    return render(request, 'auth/success.html')

src/recipes/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView   #to display lists
from .models import Recipe                #to access Recipes model
#to protect class-based view
from django.contrib.auth.mixins import LoginRequiredMixin
#to protect function-based views
from django.contrib.auth.decorators import login_required
from .forms import RecipesSearchForm
import pandas as pd
from .utils import get_chart



# Create your views here.

def home(request):
    return render(request, 'recipes/recipes_home.html')

# Create your views here.
class RecipeListView(LoginRequiredMixin, ListView):           #class-based view
    model = Recipe                         #specify model
    template_name = 'recipes/main.html'    #specify template 

class RecipeDetailView(LoginRequiredMixin, DetailView):                       #class-based view
    model = Recipe                                        #specify model
    template_name = 'recipes/detail.html'                 #specify template

#define function-based view - records(records()
@login_required
def records(request):
    # create an instance of RecipesSearchForm that you defined in recipes/forms.py
    form = RecipesSearchForm(request.POST or None)
    recipe_df = None  # initialize dataframe to None
    recipe_diff = None
    chart = None
    qs = None
    # check if the button is clicked
    if request.method == 'POST':
        recipe_diff = request.POST.get('recipe_diff')  # read recipe_name
        chart_type = request.POST.get('chart_type')  # read recipe chart type

        recipe_diff_data = {"#1": "Easy", "#2": "Medium",
                            "#3": "Intermediate", "#4": "Hard"}
        recipe_diff = recipe_diff_data[recipe_diff]

        # if recipe_diff == '#1':
        #     recipe_diff = 'Easy'
        # if recipe_diff == '#2':
        #     recipe_diff = 'Medium'
        # if recipe_diff == '#3':
        #     recipe_diff = 'Intermediate'
        # if recipe_diff == '#4':
        #     recipe_diff = 'Hard'

        qs = Recipe.objects.all()  # apply filter to extract data
        id_searched = []
        for obj in qs:
            diff = obj.calculate_difficulty()
            if diff == recipe_diff:
                id_searched.append(obj.id)

        qs = qs.filter(id__in=id_searched)

        if qs:  # if data found
            # convert the queryset values to pandas dataframe
            recipe_df = pd.DataFrame(qs.values())
            chart = get_chart(chart_type, recipe_df,
                            labels=recipe_df['name'].values)

            # convert the dataframe to HTML
            recipe_df = recipe_df.to_html()

            for item in qs.values():
                item_id = item["id"]
                item_name = item["name"]
                recipe_df = recipe_df.replace(
                    f"<td>{item_name}</td>",
                    f'<td><a href = "/recipes/list/{item_id}">{item_name}</td>'
                )

    # print(recipe_df)
    # pack up data to be sent to template in the context dictionary
    context = {
        'form': form,
        'recipe_df': recipe_df,
        'recipe_diff': recipe_diff,
        'chart': chart,
        'qs': qs,
    }
    # load the recipes/records.html page using the data that you just prepared
    return render(request, 'recipes/records.html', context)

src/users/views.py
from django.shortcuts import render

# Create your views here.

src/recipes/templates/recipes/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>BURGER | Details</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSS CUSTOM -->
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/styles.css' %}">
</head>

<body class="body">
    <div class="nav-bar">
        <a class="back-home_btn" href="/home"> Home </a>
        <a href="{%url 'recipes:records' %}" class="logout_btn">Search</a>
        <a href="{%url 'logout' %}" class="logout_btn">Logout</a>
    </div>
    <div class="details_modal">
        <h2>Details: {{object.name}}</h2>
        <div class="details_body">
        <div class="details_short">
            <b>Name: </b> {{object.name}} <br>
            <b>Cooking Time (min): </b> {{object.cooking_time}} <br>
            <b>Difficulty: </b> {{object.calculate_difficulty}} <br><br>
            <img src="{{object.pic.url}}" width="200" />
        </div>

        <div class="details_long">
            <b>Ingredients: </b> {{object.ingredients}} <br><br>
        </div>
        </div>
    </div>
</body>

</html>

src/recipes/templates/recipes/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
   <title>Burger | Recipes</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <!-- CSS CUSTOM -->
   <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/styles.css' %}">
</head>

<body>
      <div class="nav-bar">
         <div class="search_box" style="margin-top: 15px;">
            <form action="" method="GET" class="form">
            {% csrf_token %}
            <input type="text" name="recipe_search" class="form_search_input" id="searchbar" placeholder="Search Recipes..."
               onkeyup="search_recipe()" />
            </form>
            <br>
            <div class="search_results" autocomplete="off" style="display: none;">
            {% for object in object_list %}
            <p class="recipe_searched">
               <a class="recipe_name"
                  style="font-size: 18px; font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;"
                  href="{{object.get_absolute_url}}"> {{object.name}} </a>
            </p>
            {% endfor %}
            </div>
         </div>
         <div>
            <a class="back-home_btn" href="/home" style="margin: 20px;"> Home </a>
            <a href="{%url 'recipes:records' %}" class="logout_btn" style="margin: 20px;">Search</a>
            <a href="{%url 'logout' %}" class="logout_btn" style="margin: 20px;">Logout</a>
         </div>
      </div>

      <div class="recipe_grid">
         {% for object in object_list %} {% comment%} now go through the list element-by-element {% endcomment%}
         <div class="grid_item">
            <h4><a class="recipe_name" href="{{object.get_absolute_url}}"> {% comment%} add links to recipe names {%
               endcomment%}
               {{object.name}} </a> {% comment%} print the name of recipe {% endcomment%} </h4>
            <div style="margin-bottom: 10px;">
            <b>Name: </b> {{object.name}} <br>
            <b>Cooking Time: </b> {{object.cooking_time}} <br>
            <b>Difficulty: </b> {{object.calculate_difficulty}} <br>
            </div>
            <img class="food_images" src="{{object.pic.url}}" /> {% comment%} display the picture of recipe {% endcomment%}
         </div>
         {% endfor %}
      </div>
      <!-- linking javascript -->
      <script src="{% static 'recipes/js/home.js' %}"></script>
</body>

</html>

src/recipes/templates/recipes/recipes_home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>BURGER | Home</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <!-- CSS CUSTOM -->
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/styles.css' %}">
    <style type="text/css">
        img {
        border-radius: 15px;
        }

        h1,
        h3 {
        font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        color: rgb(0, 0, 255);
        }
    </style>
</head>

<body class="body" style="margin-top: 15vh;">
    <img src="{% static 'recipes/images/welcome.jpeg' %}" width="300px" height="300px">
    <h1>Welcome to Burger Recipe App</h1>
    <h3>Log-in to your account to see our list of burger recipes</h3>
    <div>
        {% if request.user.is_authenticated %}
        <a href="{%url 'logout' %}" class="logout_btn" style="margin: 40px;"> Logout </a>
        <a href="{%url 'recipes:records' %}" class="logout_btn" style="margin: 40px;">Search</a>
        {% else %}
        <a href="{%url 'login' %}" class="login_btn" style="margin: 40px;"> Login </a>
        {% endif %}
        <a href="\recipes/list" class="back-home_btn"> List </a>
    </div>
</body>

</html>

src/recipes/templates/recipes/records.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Burger | Recipes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <!-- CSS CUSTOM -->
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/styles.css' %}">
    <style type="text/css">
        body {
        font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        }

        h1 {
        font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        color: rgb(207, 206, 149);
        }

        .form_data {
        background-color: rgba(0, 0, 0, 0.61);
        border-radius: 10px;
        padding: 20px;
        }
    </style>
</head>

<body class="body">
    <div class="nav-bar">
        <a class="back-home_btn" href="/home"> Home </a>
        <a href="\recipes/list" class="back-home_btn"> List </a>
        <a href="{%url 'logout' %}" class="logout_btn">Logout</a>
    </div>
    <h1 style="font-size: 40px">Search for burger recipes in database</h1>
    <hr>
    <form action="" method="POST" class="form_data" style="margin-bottom: 20px;">
        {% csrf_token %}
        {{form}}
        <button type="submit">search</button>
    </form>
    <br>
    <br>
    {% if recipe_df %}
    {{recipe_df|safe}}
    <br>
    <img alt='chart' src="data:image/png;base64, {{chart|safe}}">
    {% else %}
    <h3> no data</h3>
    {% endif %}
</body>

</html>